from pathlib import Path

APP_NAME = "Lupa Digital"
VERSION = "0.2.0"
WINDOW_TITLE = f"{APP_NAME} V{VERSION} - Perfil Baixa Visão / Creative VF0780"

CAMERA_INDEX = 2
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30
CAMERA_BUFFER_SIZE = 1
PREFER_MJPG = True

# Faixa principal de leitura para preservar detalhes da câmera 720p.
ZOOM_LEVELS = [1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5]
DEFAULT_ZOOM_INDEX = 2  # 1.5x

PAN_STEP = 0.065

# Qualidade máxima para a ampliação.
UPSCALE_QUALITY = "maxima"

# Melhorias de leitura.
ENABLE_AUTO_GAMMA = True
AUTO_GAMMA_TARGET = 0.50

ENABLE_CLAHE = True
CLAHE_CLIP_LIMIT = 2.0
CLAHE_TILE_GRID = (8, 8)

ENABLE_DENOISE = True
DENOISE_STRENGTH = 3

ENABLE_SHARPEN = True
SHARPEN_BASE_STRENGTH = 0.68

# Assistência para posicionar câmera e iluminação.
ENABLE_QUALITY_ASSIST = True
SHARPNESS_LOW = 55.0
SHARPNESS_GOOD = 115.0
BRIGHTNESS_DARK = 65.0
BRIGHTNESS_BRIGHT = 205.0
QUALITY_ROI_SCALE = 0.72

# Interface.
START_FULLSCREEN = False
SHOW_HUD = True
SHOW_READING_GUIDE = False
READING_GUIDE_Y = 0.53
READING_GUIDE_HEIGHT = 84
SHOW_READING_MARKERS = True

DEFAULT_READING_MODE_INDEX = 0

SCREENSHOT_DIR = Path("capturas")
